name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight
  workflow_dispatch:

jobs:
  ros1_bridge:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ros1:
          - distro: noetic
        ros2:
          - distro: foxy
          #- distro: rolling

    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: "${{matrix.ros1.distro}} ${{matrix.ros2.distro}}"
      - id: custom_build_sequence
        name: custom_build_sequence
        run: |
          sudo apt install ros-${{matrix.ros2.distro}}-ros1-bridge -y
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: ros1_bridge
          target-ros1-distro: ${{matrix.ros1.distro}}
          target-ros2-distro: ${{matrix.ros2.distro}}

